### ISSUE TITLE
implement proper layout

### ISSUE THREAD

**Issue by awitherow** [awitherow/openrefuge#14]
currently the app vue is structured so...

```
<template>
  <div id="app">
    <site-header />
    <transition name="fade">
      <router-view></router-view>
    </transition>
  </div>
</template>
```

the app has a set height: 100vh, and the container class is sort of a flex full width container

```
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  flex-direction: column;
  max-width: 900px;
  margin: 0 auto;
  padding: 0 15px;
}
```

the idea is to have a fixed header (sticky), a fixed (also sticky) footer, and a scrollable content in the middle that expands to fill in the space above.

What is the simplest way to implement this?

# action

- [x] fix current state of header and container https://github.com/openrefuge/openrefuge/pull/16
- [ ] how do we implement footer ideas?

**Comment by dazulu** [comment]
With what you told me, I wouldn't use flexbox for layout. Just regular old stuff.

**Comment by awitherow** [comment]
@dazulu changed the title then :) sorry, you know I am a newbie with css. That is why I have prayed to the cssgods for your help.

**Comment by awitherow** [comment]
@dazulu could you review the referenced PR?

**Comment by awitherow** [comment]
woot! this is done baby.
